name: accident_predictor_env
dependencies:
  - python=3.6
  - numpy
  - pymongo
  - hdf5
  - h5py
  - pillow
  - pytest
  - plotly
  - scipy
  - numba
  - scikit-learn
  - pip:
    - namedlist
    - tensorflow
    - keras
    - opencv-python
